kind: Deployment
apiVersion: apps/v1
metadata:
  name: mparticle-transform-consumer-<PRODUCT>-prod
  namespace: airlytics
  labels:
    app: mparticle-transform-consumer
  annotations:
    deployment.kubernetes.io/revision: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mparticle-transform-consumer
  template:
    metadata:
      labels:
        app: mparticle-transform-consumer
    spec:
      nodeSelector:
        pod-type: <POD_TYPE>
      containers:
        - name: mparticle-transform-consumer
          image: <IMAGE_STORE_SERVER>/airlytics/consumer:latest
          args: ["mparticle_transform"]
          ports:
            - containerPort: 8084
              name: metrics
              protocol: TCP
          env:
            - name: AIRLYTICS_ENVIRONMENT
              value: 'PROD'
            - name: AIRLYTICS_PRODUCT
              value: '<PRODUCT>'
            - name: METRICS_PORT
              value:  '8084'
            - name: AIRLYTICS_DEPLOYMENT
              valueFrom:
                configMapKeyRef:
                  name: airlytics-deployments-config
                  key: airlytics.deployment
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              memory: 1G
            requests:
              memory: 1G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600