kind: Deployment
apiVersion: apps/v1
metadata:
  name: raw-data-consumer-[product]-[topic-type]
  namespace: airlytics
  labels:
    app: raw-data-consumer
  annotations:
    deployment.kubernetes.io/revision: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raw-data-consumer
  template:
    metadata:
      labels:
        app: raw-data-consumer
    spec:
      nodeSelector:
        pod-type: <POD_TYPE>
      containers:
        - name: raw-data-consumer
          image: <IMAGE_STORE_SERVER>/airlytics/consumer:latest
          args: ["rawdata"]
          ports:
            - containerPort: 8084
              name: metrics
              protocol: TCP
          env:
          #  - name: AIRLOCK_USER_GROUPS
          #    value: 'Dev'
            - name: AIRLYTICS_ENVIRONMENT
              value: 'DEV'
            - name: AIRLYTICS_PRODUCT
              value: '<PRODUCT>'
            - name: METRICS_PORT
              value:  '8084'
            - name: AIRLYTICS_RAWDATA_SOURCE
              value:  'SUCCESS'
            - name: AIRLYTICS_DEPLOYMENT
              valueFrom:
                configMapKeyRef:
                  name: airlytics-deployments-config
                  key: airlytics.deployment
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600