CREATE ROLE redash 
NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN PASSWORD '<pass5>';
GRANT CREATE ON DATABASE redash TO redash;
REVOKE ALL PRIVILEGES ON SCHEMA redash.public FROM PUBLIC;
GRANT ALL PRIVILEGES ON SCHEMA public TO redash;