kind: Service
apiVersion: v1
metadata:
  name: compaction-consumer
  namespace: airlytics
  labels:
    app: compaction-consumer
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: 8084
    targetPort: 8084
  selector:
    app: compaction-consumer