apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: airlytics-prometheus
  name: airlytics-prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    prometheus: airlytics-prometheus
  type: NodePort
  sessionAffinity: ClientIP
