{
 "title": "Retention",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Query for platform",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (platform) (rate(retention_tracker_query_for_platform_total{service=\"retention-tracker-db-handler\"}[5m]))",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "Query for platform",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(retention_tracker_query_for_platform_total{service=\"retention-tracker-db-handler\",platform=\"ios\"}[1m])",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "rate(retention_tracker_query_for_platform_total{service=\"retention-tracker-db-handler\",platform=\"android\"}[1m])",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "Total query for platform (android)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(retention_tracker_query_for_platform_total{platform=\"android\",service=\"retention-tracker-db-handler\"})",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "Total query for platform (iOS)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(retention_tracker_query_for_platform_total{platform=\"ios\",service=\"retention-tracker-db-handler\"})",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "Inactive Users",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "retention_tracker_inactivated_users_total",
     "legendFormat": "Inactive users"
    }
   ]
  },
  {
   "title": "Deleted Users",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(retention_tracker_deleted_users_total)",
     "legendFormat": "Deleted Users"
    }
   ]
  }
 ]
}
{
 "title": "Consumers",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "platform", "label": "Platform", "query": "ios, android" },
   { "name": "env", "label": "Environment", "query": "prod, dev" },
   {
    "name": "node",
    "label": "Node",
    "query": "ip-172-31-1-90.ec2.internal, ip-172-31-20-216.ec2.internal, ip-172-31-23-25.ec2.internal, ip-172-31-4-181.ec2.internal, ip-172-31-66-180.ec2.internal, ip-172-31-79-211.ec2.internal"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Stat (average)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(100 - (irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) * 100) by (instance)",
     "legendFormat": "{{instance}} CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "{{instance}} RAM"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}  Storage"
    }
   ]
  },
  {
   "title": "Cloned Events Counter (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(airlytics_cloning_records_processed_total{pod=~\".*$platform.*\", pod=~\".*$env.*\"}[1m]))",
     "legendFormat": "events"
    }
   ]
  },
  {
   "title": "Cloning Request Median",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(airlytics_cloning_proxy_time_seconds_bucket[1m])) by (le))",
     "legendFormat": "median"
    }
   ]
  },
  {
   "title": "Cloning Request time 0.95-quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(airlytics_cloning_proxy_time_seconds_bucket[1m])) by (le))",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Compaction Unmerged Data (per day)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(compaction_unmerged_data_size_MB{pod=~\".*$platform.*\", pod=~\".*$env.*\"}) by (day) > 50)",
     "legendFormat": "{{day}}"
    }
   ]
  },
  {
   "title": "Compaction Unmerged Data Total (per range, per instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(compaction_unmerged_data_size_MB{pod=~\".*$platform.*\", pod=~\".*$env.*\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compaction Consumer Queue Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airlytics_compaction_waiting_tasks{env=~'$env', platform=~'$platform'}",
     "legendFormat": "queue size {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Statistic (per node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(100 - (irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m]) * 100)) by (instance)",
     "legendFormat": " finer detail {{instance}}"
    },
    {
     "expr": "sum(100 - (rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m]) * 100)) by (instance)",
     "legendFormat": "average rate {{instance}}"
    }
   ]
  },
  {
   "title": "UserDB Records Successfully Processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(airlytics_userdb_records_processed_total{result=\"success\",env=~'$env', platform=~'$platform'}[$__range])) by (event_name) ",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "UserDB Records Successfully Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(airlytics_userdb_records_processed_total{result=\"success\",env=~'$env', platform=~'$platform'}[$__range])) by (event_name) ",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "UserDB Records Processing Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(airlytics_userdb_records_processed_total{result=\"error\",env=~'$env', platform=~'$platform'}[$__range])) by (event_name) ",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Persistence Total Processed Records (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(airlytics_persistence_records_processed_total{result=\"success\",env=~'$env', platform=~'$platform'}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UserDB Records (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(airlytics_userdb_records_processed_total{env=~'$env', platform=~'$platform'}[5m]))",
     "legendFormat": "events"
    }
   ]
  },
  {
   "title": "Persistence Total Processed Records (per sec, per node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(airlytics_persistence_records_processed_total{env=~'$env', platform=~'$platform'}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UserDB Records (per sec, per node)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(airlytics_userdb_records_processed_total{env=~'$env', platform=~'$platform'}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raw Data Total Processed Records (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(airlytics_rawdata_records_processed_total{result=\"success\",env=~'$env', platform=~'$platform'}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compaction Total Processed Records (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(airlytics_compaction_records_processed_total{env=~'$env', platform=~'$platform'}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Persistence Total Written Files (per pod, range)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(airlytics_persistence_files_written_total{result=\"success\",env=~'$env', platform=~'$platform'}[$__range])",
     "legendFormat": "success {{instance}}"
    },
    {
     "expr": "increase(airlytics_persistence_files_written_total{result=\"error\",env=~'$env', platform=~'$platform'}[$__range])",
     "legendFormat": "error {{instance}}"
    }
   ]
  },
  {
   "title": "Total Userdb Cache Lookups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(airlytics_userdb_cache_lookups_total{env=~'$env', platform=~'$platform'}[$__range])) by (hit)",
     "legendFormat": "{{hit}} "
    }
   ]
  },
  {
   "title": "User DB  Query Latency  (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(airlytics_userdb_db_latency_seconds_sum{env=~'$env', platform=~'$platform'}*1000)/sum(airlytics_userdb_db_latency_seconds_count{env=~'$env', platform=~'$platform'})",
     "legendFormat": "average latency "
    }
   ]
  },
  {
   "title": "Persistence  File Sizes in Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airlytics_persistence_file_size_bytes_sum{env=~'$env', platform=~'$platform'}"
    }
   ]
  }
 ]
}