kind: Service
apiVersion: v1
metadata:
  name: secure-grafana-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <cert-arn> #replace this value
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  namespace: monitoring
  labels:
    app: secure-grafana-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
  externalTrafficPolicy: Cluster
  selector:
    app: grafana-sso
  type: LoadBalancer



