{
 "title": "Event Proxy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "platform", "label": "Platform", "query": "android, ios" },
   { "name": "mode", "label": "Mode", "query": "dev, prod" },
   {
    "name": "node",
    "label": "Node",
    "query": "ip-172-31-10-100.ec2.internal,  ip-172-31-64-172.ec2.internal, ip-172-31-17-237.ec2.internal"
   }
  ]
 },
 "panels": [
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {}
   ]
  },
  {
   "title": "Current Errors (per range)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(event_proxy_event_failures_counter{platform=~\"$platform\",env=~\"$mode\"}[$__range]))",
     "legendFormat": "failed events"
    }
   ]
  },
  {
   "title": "Events and Requests Counter (per sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(event_proxy_event_counter{platform=~\"$platform\",env=~\"$mode\"}[1m]))",
     "legendFormat": "events"
    },
    {
     "expr": "sum(rate(event_proxy_request_counter{platform=~\"$platform\",env=~\"$mode\"}[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Events Counter Per Node (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(event_proxy_event_counter{platform=~\"$platform\",env=~\"$mode\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " Percentage of Errors from Total Events (per sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(event_proxy_event_failures_counter{platform=~\"$platform\",env=~\"$mode\"}[1m]))*100/sum(rate(event_proxy_event_counter{platform=~\"$platform\",env=~\"$mode\"}[1m]))",
     "legendFormat": "errors / total events"
    }
   ]
  },
  {
   "title": "Errors Counter (per sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(event_proxy_event_failures_counter{platform=~\"$platform\",env=~\"$mode\"}[1m])) by (errorType)",
     "legendFormat": "{{errorType}}"
    },
    {}
   ]
  },
  {
   "title": "UserDB Records Successfully Processed (per range)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(airlytics_userdb_records_processed_total{result=\"success\",env=~'$mode', platform=~'$platform'}[1m])) by (event_name) ",
     "legendFormat": "{{event_name}}"
    },
    {}
   ]
  },
  {
   "title": "UserDB Records Successfully Processed (per range)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(sum(increase(airlytics_userdb_records_processed_total{result=\"success\",env=~'$mode', platform=~'$platform'}[$__range])) by (event_name))",
     "legendFormat": "<div style='max-width:100px'>{{event_name}}</div>"
    }
   ]
  },
  {
   "title": "Event Types (per range)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(sum(increase(event_proxy_event_counter{platform=~\"$platform\",env=~\"$mode\"}[$__range])) by (event_name))",
     "legendFormat": "<div style='max-width:100px'>{{event_name}}</div>"
    }
   ]
  },
  {
   "title": "Error Types (per range, per type)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(sum(increase(event_proxy_event_failures_counter{platform=~\"$platform\",env=~\"$mode\"}[$__range])) by (errorType))",
     "legendFormat": "{{errorType}}"
    }
   ]
  },
  {
   "title": "Error Types (per range, per event name)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(sum(increase(event_proxy_event_failures_counter{platform=~\"$platform\",env=~\"$mode\"}[$__range])) by (event_name))",
     "legendFormat": "{{event_name}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Kafka Errors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 64 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(event_proxy_kafka_error_counter[$__range]))"
    }
   ]
  },
  {
   "title": "Kafka Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(event_proxy_kafka_error_counter{platform=~\"$platform\",env=~\"$mode\"}[1m]))"
    }
   ]
  },
  {
   "title": "Response Time (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(event_proxy_response_time_bucket{platform=~\"$platform\",env=~\"$mode\",le=\"+Inf\"}[$__range]))-sum(increase(event_proxy_response_time_bucket{platform=~\"$platform\",env=~\"$mode\",le=\"200\"}[$__range]))",
     "legendFormat": "> 200 ms"
    }
   ]
  }
 ]
}