{
 "title": "Consumers  JVM  Overview",
 "description": "Dashboard for Consumers JVM ",
 "tags": [
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" },
   { "name": "service", "label": "Consumer", "query": "label_values(service)" },
   { "name": "platform", "label": "Platform", "query": "android, ios" },
   { "name": "env", "label": "Environment", "query": "prod, dev" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$instance\", service=~\"$service\", pod=~\".*$platform.*\", pod=~\".*$env.*\"}[1m])",
     "legendFormat": "{{instance}}",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Memory Used/Maximum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=~\"$instance\", service=~\"$service\", pod=~\".*$platform.*\", pod=~\".*$env.*\"}) by (instance)",
     "legendFormat": "used {{instance}}"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{instance=~\"$instance\", service=~\"$service\", pod=~\".*$platform.*\", pod=~\".*$env.*\"}) by (instance)",
     "legendFormat": " maximum {{instance}}"
    }
   ]
  },
  {
   "title": "Threads Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\", service=~\"$service\", pod=~\".*$platform.*\", pod=~\".*$env.*\"}",
     "legendFormat": "current [{{instance}}]"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$instance\", service=~\"$service\", pod=~\".*$platform.*\", pod=~\".*$env.*\"}",
     "legendFormat": "daemon [{{instance}}]"
    }
   ]
  },
  {
   "title": "Class Loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=~\"$instance\", service=~\"$service\", pod=~\".*$platform.*\", pod=~\".*$env.*\"}",
     "legendFormat": "loaded [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$instance\", service=~\"$service\", pod=~\".*$platform.*\", pod=~\".*$env.*\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{instance=~\"$instance\", service=~\"$service\", pod=~\".*$platform.*\", pod=~\".*$env.*\"}",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  }
 ]
}