kind: Service
apiVersion: v1
metadata:
  name: secure-event-proxy-service-beta
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  namespace: airlytics
  labels:
    app: secure-event-proxy-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
  externalTrafficPolicy: Cluster
  selector:
    app: event-proxy-beta
  type: LoadBalancer