kind: Service
apiVersion: v1
metadata:
  name: retention-tracker-push-handler
  namespace: airlytics
  labels:
    app: retention-tracker-push-handler
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: 8084
    targetPort: 8084
  selector:
    app: retention-tracker-push-handler