apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  labels:
    app: retention-tracker-push-listener
  name: retention-tracker-push-listener-<PRODUCT>
  namespace: airlytics
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: retention-tracker-push-listener
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: retention-tracker-push-listener
    spec:
      containers:
        - env:
            - name: AIRLYTICS_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: airlytics.environment
                  name: airlytics-deployments-config
            - name: USERDB_PROCESS_TYPE
              value: ios-bounce-listener
            - name: AIRLYTICS_PRODUCT
              value:  '<PRODUCT>'
            - name: AIRLYTICS_DEPLOYMENT
              valueFrom:
                configMapKeyRef:
                  key: airlytics.deployment
                  name: airlytics-deployments-config
          image: <IMAGE_STORE_SERVER>/airlytics/retention-tracker-push-handler:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: metrics
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: retention-tracker-push-listener
          ports:
            - containerPort: 8084
              name: metrics
              protocol: TCP
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        pod-type: <POD_TYPE>
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30