kind: Deployment
apiVersion: apps/v1
metadata:
  name: db-pruner-<PRODUCT>
  namespace: airlytics
  labels:
    app: db-pruner
  annotations:
    deployment.kubernetes.io/revision: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-pruner
  template:
    metadata:
      labels:
        app: db-pruner
    spec:
      nodeSelector:
        pod-type: <POD_TYPE>
      containers:
        - name: db-pruner
          image: <IMAGE_STORE_SERVER>/airlytics/userdb-periodical-process:latest
          env:
            - name: AIRLYTICS_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: airlytics-deployments-config
                  key: airlytics.environment
            - name: USERDB_PROCESS_TYPE
              value: 'pruner'
            - name: AIRLYTICS_PRODUCT
              value: '<PRODUCT>'
            - name: AIRLYTICS_DEPLOYMENT
              valueFrom:
                configMapKeyRef:
                  name: airlytics-deployments-config
                  key: airlytics.deployment
          ports:
            - containerPort: 8084
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600