kind: Service
apiVersion: v1
metadata:
  name: dsr-requests-scrapper
  namespace: airlytics
  labels:
    app: dsr-requests-scrapper
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: 8084
    targetPort: 8084
  selector:
    app: dsr-requests-scrapper