kind: Deployment
apiVersion: apps/v1
metadata:
  name: purchase-consumer-<PRODUCT>
  namespace: airlytics
  labels:
    app: purchase-consumer
  annotations:
    deployment.kubernetes.io/revision: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purchase-consumer
  template:
    metadata:
      labels:
        app: purchase-consumer
    spec:
      nodeSelector:
        pod-type: <POD_TYPE>
      containers:
        - name: purchase-consumer
          image: <IMAGE_STORE_SERVER>/airlytics/consumer:latest
          args: ["purchase"]
          volumeMounts:
            - name: google-api-key
              mountPath: "/usr/src/app/keys"
              readOnly: true
          ports:
            - containerPort: 8084
              name: metrics
              protocol: TCP
          env:
            - name: APP_PACKAGE
              value: '<PRODUCT_APP_PACKAGE>'
            - name: AIRLYTICS_ENVIRONMENT
              value: 'PROD'
            - name: AIRLYTICS_PRODUCT
              value: '<PRODUCT>'
            - name: METRICS_PORT
              value:  '8084'
            - name: USERDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userdb-secret
                  key: airlytics-all-rw
            - name: AIRLYTICS_DEPLOYMENT
              valueFrom:
                configMapKeyRef:
                  name: airlytics-deployments-config
                  key: airlytics.deployment
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              memory: 2G
            requests:
              memory: 2G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      volumes:
      - name: google-api-key
        secret:
          secretName: google-api-secret
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600