kind: Service
apiVersion: v1
metadata:
  name: ltv-reader-braze
  namespace: airlytics
  labels:
    app: ltv-reader-braze
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 8084
      targetPort: 8084
  selector:
    app: ltv-reader-braze