kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: consumers-aws-efs
  namespace: airlytics
  annotations:
    volume.beta.kubernetes.io/storage-class: "consumers-aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi