kind: Service
apiVersion: v1
metadata:
  name: userdb-parquet-dumper
  namespace: airlytics
  labels:
    app: userdb-parquet-dumper
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: 8084
    targetPort: 8084
  selector:
    app: userdb-parquet-dumper