kind: Service
apiVersion: v1
metadata:
  name: ltv-aggregator-<PRODUCT>
  namespace: airlytics
  labels:
    app: ltv-aggregator-<PRODUCT>
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: 8084
    targetPort: 8081
  selector:
    app: ltv-aggregator-<PRODUCT>