kind: Deployment
apiVersion: apps/v1
metadata:
  name: ai-data-import-<PRODUCT>-prod
  namespace: airlytics
  labels:
    app: ai-data-import-<PRODUCT>-prod
  annotations:
    deployment.kubernetes.io/revision: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-data-import-<PRODUCT>-prod
  template:
    metadata:
      labels:
        app: ai-data-import-<PRODUCT>-prod
    spec:
      nodeSelector:
        pod-type: <POD_TYPE>
      containers:
        - name: ai-data-import
          image: <IMAGE_STORE_SERVER>/airlytics/ai-data-import:latest
          ports:
            - containerPort: 8081
              name: web
              protocol: TCP
          env:
            - name: AIRLYTICS_ENVIRONMENT
              value: 'PROD'
            - name: AIRLYTICS_PRODUCT
              value: '<PRODUCT>'
            - name: AIRLYTICS_DEPLOYMENT
              valueFrom:
                configMapKeyRef:
                  name: airlytics-deployments-config
                  key: airlytics.deployment
            - name: DB_URL
              value: 'jdbc:postgresql://<DB_SERVER>:5432/users?currentSchema=<PRODUCT>'
            - name: DB_USER_NAME
              value: 'airlytics_data_import'
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userdb-secret
                  key: airlytics_data_import
            - name: AIRLOCK_KEY
              valueFrom:
                secretKeyRef:
                  name: airlock-api-secret
                  key: airlock-key
            - name: AIRLOCK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airlock-api-secret
                  key: airlock-password
          livenessProbe:
            httpGet:
              path: /healthcheck/is-alive
              port: web
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthcheck/is-ready
              port: web
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600