apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceapp: ai-data-import-<PRODUCT>-prod-service-monitor
  name: ai-data-import-<PRODUCT>-prod-service-monitor
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 15s
      port: metrics
  namespaceSelector:
    matchNames:
      - airlytics
  selector:
    endpoints:
      - port: metrics
    matchLabels:
      app: ai-data-import-<PRODUCT>-prod
